version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ielts-vocabulary-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ielts-vocabulary
    volumes:
      - mongodb_data:/data/db
    networks:
      - ielts-vocabulary-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ielts-vocabulary-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ielts-vocabulary
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-2024
      - JWT_EXPIRES_IN=7d
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - FRONTEND_URL=http://localhost:3000
      - PORT=3001
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ielts-vocabulary-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/vocabulary/topics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ielts-vocabulary-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ielts-vocabulary-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  ielts-vocabulary-network:
    driver: bridge